baseURL = 'https://hogus.work/'
theme = "hogusource"
languageCode = "ja"
title = "hogusource codes"
[outputs]
home = ["HTML", "RSS", "JSON"]
section = ["HTML", "RSS", "JSON"]
taxonomy = ["HTML", "RSS"]
term = ["HTML", "RSS"]
[markup]
  [markup.highlight]
    style = "dracula"
    lineNos = false
    noClasses = false
